"""empty message

Revision ID: 31306a3a0b4d
Revises: f92c5b8b45ba
Create Date: 2021-01-26 23:49:50.982010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31306a3a0b4d'
down_revision = 'f92c5b8b45ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('heure_degele', sa.DateTime(), nullable=True))
    op.add_column('ticket', sa.Column('heure_gele', sa.DateTime(), nullable=True))
    op.add_column('ticket', sa.Column('heure_validation', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'heure_validation')
    op.drop_column('ticket', 'heure_gele')
    op.drop_column('ticket', 'heure_degele')
    # ### end Alembic commands ###
