"""empty message

Revision ID: f92c5b8b45ba
Revises: 91f31ec83d6b
Create Date: 2021-01-25 22:16:51.634480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f92c5b8b45ba'
down_revision = '91f31ec83d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cil', sa.Column('adresse', sa.String(length=260), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cil', 'adresse')
    # ### end Alembic commands ###
